# Generated by Django 2.1.5 on 2019-05-10 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=20)),
                ('project_content', models.TextField()),
                ('project_published', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 13, 47, 29, 972375), verbose_name='date published')),
            ],
        ),
    ]
