# Generated by Django 2.1.5 on 2019-05-10 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=20)),
                ('project_content', models.TextField()),
                ('project_published', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 17, 24, 7, 785063), verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
