# Generated by Django 2.1.5 on 2019-05-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190510_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_published',
        ),
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_host',
            field=models.URLField(default=''),
        ),
    ]
