# Generated by Django 2.1.5 on 2019-05-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190516_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_host',
            field=models.URLField(blank=True, default=''),
        ),
    ]
